In [2]:
'''
module_6
NumPy Assignment
'''
import numpy as np

In [11]:
'''
Q1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?
Answer:
    Numpy (Numerical Python) is a powerful library in python designed for performing efficient 
    and high speed mathematical operations, particularly on large datasets.
    Its main purpose is to provide support for multidimensional arrays (often called ndarrays)
    Numpy pakage is a fundamental package in python for efficient numerical computations and data
    manipulation, especially useful in scientific computing and data analysis.
    Its primary goal is to enhance python's capabilities for handling large datasets and performing
    complex mathematical operations
Advantages of Numpy are as following:
    1.Efficient Storage and Performance:
        Numpy arrays are more efficient in both speed and memory compared to python's native list.
Example:      
'''
a =  np.array([1, 2, 3, 4, 5])
print(a.nbytes)
'''
    2.Support for Multi-dimensional Arrays:
        Numpy can handle multi-dimensional arrays, making it essential for complex data structure 
        like matrices, 3D tensors, etc.
Exmaple:        
'''
matrix = np.matrix([[1, 2], [3, 4]])
print(matrix.shape)
'''
    3.Vectorized Operations:
        operations on arrays are done without explicit loops, resulting in faster and clearner code.
Example:
'''

a =[1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 10]
arr = np.array(a)
arr2 = np.array(b)
print(arr+arr2)  # 7, 9, 11, 13, 15
'''
    4. Wide Range of Mathematical Functions:
        It provides mathematical functions such as mean, standard deviation, matrix operations, 
         and more for complex computation.
Example:
'''
data = np.array([10, 20, 30, 40, 50])
print(np.mean(data))
'''
    5. Broadcast:
        I allows operations on array of different sizes without needing to duplicate data,
        optimizing memory usage
'''
arr = np.array([1, 2, 3])
b = 5         # 5, 7, 8
print(arr + b)
'''
    6. Integration with other Library:
        Numpy integrates seamlessly with data science libraries like Pandas, SciP and Tensorflow.
    7. It includes utility to generate random numbers for simulations and stochastic process.
Example:
'''
random_array = np.random.rand(3,3)
print(random_array)
'''
How it is enhances python's Capabilities?:
    Without Numpy, Python's builtin data structures are not optimized for numerical operations on large datasets.
Numpy Provides:
    Faster computations: By handling operations at a lower level using C.
Memory Efficient:
    Through fixed_size, homogenous arrays.
Vectorized operations:
    That avoids the need for loops, leading to clearner and more efficient code.
    
Insights:
    Numpy is a cornerstone for scientific computing in python. It accelerates numerical operations, offers's 
    memory efficiency, and integrated with essential libraries like pandas, making it indispensable
    for data science tasks.
'''
print()

40
(2, 2)
[ 7  9 11 13 15]
30.0
[6 7 8]
[[0.38703873 0.83947919 0.45492626]
 [0.48320166 0.92866625 0.6897496 ]
 [0.90250224 0.35332846 0.25694088]]



In [12]:
'''
Q2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?
Answer:
    Difference between np.mean() and np.average in Numpy are as following:
1.Purpose:
    1.np.mean(): This function calculates the regular of numbers, treating all numbers equality.
    
    2.np.average(): This function can alose calculate the average, 
    but it allows you to give different importance (weights) to each number.
2. How They work:
    1.np.mean() (syntax):
    numpy.mean(array)
    #It simplify finds the average of all the numbers in the array.

    2.np.average(array)
    numpy.mean(array,weights=weights_array)
    #It finds the average, but you can also provide weights. Numbers with higher weights will have more influence
    on the result
Examples:
'''
#Using np.mean()
arr = [1, 2, 3, 4, 5]
mean_array = np.mean(arr)
print(mean_array)

# Using np.average()
arr = [1, 2, 3, 4 ,5]
weights = [1, 2, 3, 4, 5]
weighted_avg = np.average(arr,weights=weights)
print(weighted_avg)
'''
When to use Them:
    1.np.mean(): When all numbers are equally important, means when you want a quick average
    without considering any weights.
    It is straightforward and efficient for basic calculations.
    2.np.average(): When some numbers should have more influence on the result than others(eg,weighted grading systems),
    When you need to calculate an average that takes into account, the importance of 
    each number.(eg, if you are calculating a final grade where some assignments are worth more than others, 
    np.average() lets you do that easily.
    
Insights:
    Choosing between np.mean() and np.average() depends on your analysis needs:
    1.Use np.mean() for quick calculations(simple calculations) and 
    2.np.average() when you need an weighted results(the contribution of each number)
'''
print()

3.0
3.6666666666666665



In [3]:
import numpy as np
'''
Q3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.
Answer:
    To reverse a Numpy array along different axes, you can use slicing([::-1]) or the np.flip()
    function.
    The codes for this approach are as following    
Method_1:
    You can reverse an array along any axis by slicing it.
    The syntax for reversing along a specific axis is as following
array[::-1] #reverses  along the axis (rows)
array[:,::-1] # reverse along the second axis (columns)

Method_2:
    Numpy's np.flip() method reverses an array along a specified axis.
    The syntax is as following:
np.flip(array, axis)

    Where axis = 0 reverses the first axis (rows), axis = 1 reverses the second axis(columns), etc.

Example_1: Reverse a 1D array (length 10)
'''
array_1d = np.arange(10)
print(f"Original array containing 10 elements:\t{array_1d}")
reversed_1d = array_1d[::-1] # This will reverses the rows
print(f"Reversed 1Dimension Array:\t{reversed_1d}")
'''
Example_2: Reverse a 2D array (shape 4x5, total 20 elements)
    In a 2D array, you can reverse along different axes.
'''
array_2d = np.arange(20).reshape(4, 5)
print("Original 2Dimension Array:\n", array_2d)
reversed_rows = np.flip(array_2d, axis=0)
print(f"Reversed Rows Array:\n{reversed_rows}")


reversed_columns = np.flip(array_2d, axis=1)
print(f"Reversed Column Array:\n{reversed_columns}")
'''
Insights:
    use slicing ([::-1]) for simple 1Dimension and np.flip() for multi dimension arrays where 
    specific axes needs to be reserved.
'''
print()

Original array containing 10 elements:	[0 1 2 3 4 5 6 7 8 9]
Reversed 1Dimension Array:	[9 8 7 6 5 4 3 2 1 0]
Original 2Dimension Array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Reversed Rows Array:
[[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]
Reversed Column Array:
[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]



In [4]:
'''
Q4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance?
Answer:
    To determine the data type of elements in a Numpy array, you can use the dtype attribute of the array.
Example:
'''

num_arr = np.array([1,2,3])
print("Number Array: ",num_arr)
print("Determined Data type :", num_arr.dtype)
'''
This will show the data type(dtype) of the elements in the array.

Importance of Data Types in Memory Management and Performance:
    1.Memory Efficiency:
        Data types (dtypes) in Numpy control how much memory each element of an array consumes, 
        for example: an int32 type takes 4 bytes per element, while an int64 type takes 8 bytes.
        
        Choosing the right data can save memory, especially when dealing with large datasets.
        for example: if you dont need large integers, using int32 instead of int 64 can cut the memory usage by half
    
    2.Performance:
        Smaller data types allow faster computation because the CPU processes smaller amounts of data at a time.
        For instance, operations on float 32 array can be faster the float64 arrays since float32 uses less memory
        and thus, data can be loaded into the CPU more efficiently.
        
        However, if you use a data type thats too small (eg:int8 when you need larger values) , it can lead,
        to overflow errror, which can crash your program or produce wrong results.
    
    3.Compatibility:
        choosing the right data type is crucial when interfacing with other systems like databases or hardware.
        if the data types dont match , it can lead to conversion overhead or data loss.
        
        In certain machine learning and scientific computing applications, specific data types like float32 are 
        often preferred due to their balance between precision and performance.

Insights:
    Understanding and selecting appropriate data types in Numpy is important for optimizing memory usage and ensuring 
    fast computations. 
    By carefully choosing the smallest data type that meets your precision needs, you can significantly 
    enhance the performance of you code, especially when working with larger data sets or
     in performance-critical applications.
'''
print()

Number Array:  [1 2 3]
Determined Data type : int64



In [7]:
'''
Q5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
Answer:
    N-dimensional array (ndarray) is the core data structure in Numpy, designed for efficient scientific 
    computing. 
    It represents a grid of values, all of the same data type, and can be multti-dimensional.
    

key Features of narray (N-dimensional array):
    1.fixed size:
        Once created, and ndarray has fixed size, meaning you cannot append or remove elements like you
        can with python list. This is fixed size allows for efficient memory management.
    2.homogenous:
        All elements in an ndarrays must be of the same type(eg: int32, float64). This uniformity compared 
        to python list, which can hold mixed types
    3.Efficient Memory Usage:
        ndarray object use continuous blocks of memory, making them more memory efficient than python lists, 
        especially for large datasets.
        This also ensures fast access to elements.
    4. Vectorized Operations:
        Numpy arrays support vectorized operations to entire arrays without the need for explicit loops. 
        This both faster and more readable than loops
    Example:
'''
arr = np.array([1,2,3])
print("original Array:\n ", arr)
result = arr * 2
print(f"result is: {result} of {arr}x2")
'''
    5.Multi-dimensional support:
        narray can handle multi-dimensional data, you can easily work with matrices , tensors and higher dimensional,
        datasets, which is not as straightforward with python list
    Example:
    '''
arr_2d = np.array([[1,2], [3, 4]])
print("It is and",arr_2d.ndim,"dimensional array")
'''
    6.Advanced Indexing:
        narray supports sophisticated slicing and Indexing techniques. allowing you to access and manipulate 
        specific parts of the array efficient.
    Example:
    '''
arr = np.array([1, 2, 3, 4, 5, 6])
print("Slicing from first index to the third:",arr[1:3])
'''
Difference Between narray and python list.
    1. Data type :
        1.narrya is homogeneous (all the elements are of the same type)
        2.python list is heterogeneous ( can contain different data types like int,str,etc, together)
    2. Memory Efficient:
        1.narray is more memory efficient as it stores data in contiguous memory blocks, 
            optimized for large numerical operations.
        2.Python list is less memory efficient since each element is an object with meta data, increasing overhead.
    3.speed:
        1.narray is much faster for numerical operations due to vectorization and fixed data types.
        2.Python list is slower, especially for large data, because it lacks vectorization and stores mixed data types.
    4.Operations:
        1.narray supports element wise operations and broadcasting, enabling complex calculations 
            in fewer lines of codes.
        2.python list requires manual iteration for element-wise operations, leading to slower an less efficient code.
    Example:
'''
# Python list
list = [1, 2, 3]
print(f"list:{list}x2")
result  = [x*2 for x in list]
print("Multiply using list comprehension ",result)

# Numpy narray
arr = np.array([1,2,3])
print(f"Array: {arr}x2")
result = arr*2
print("Multiplied using an array" ,result)
'''
Insights:
    narray in Numpy offers advantages in memory usage, speed and the ability to handle multi-dimensional data
    efficiently, while python list are more flexible for general purpose use, numpy arrays are optimized for large 
    scale numerical computations and provide a faster, more efficient alternatives.

'''
print()

original Array:
  [1 2 3]
result is: [2 4 6] of [1 2 3]x2
It is and 2 dimensional array
Slicing from first index to the third: [2 3]
list:[1, 2, 3]x2
Multiply using list comprehension  [2, 4, 6]
Array: [1 2 3]x2
Multiplied using an array [2 4 6]



In [3]:
'''
Q6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations?
Answer:
    Numpy provides significant performance benefits over python lists when handling large scale numerical,
    operations.
    The points are as following:
1.memory efficiency:
    1.Python list are arrays of pointers to objects, which can store different data types.
        The flexibility increases memory overhead.
'''
import sys
# python list#
list_ = [1, 2, 3, 4, 5]
print("Memory used for ",list_, "is", sys.getsizeof(list), "bytes")
'''
    2.Nympy's arrays stores elements in a contiguous block of memory and support only a single data type,
    making them far more efficient.
        This reduction in memory overhead leads to faster access times.
    Example:
'''
# Array list
arr_list_ = [1,2, 3, 4 ,5]
print("Memory used for array",arr_list_, "is", sys.getsizeof(arr_list_), "bytes")
'''
2.Speed:
    1.Python lists operations are executed using interpreted loops, which re relatively slow, each element in the 
        list is checked dynamically for its type, increasing computational usage.
    '''
fruits = ["Apple", "greenapple", "pineapple"]
list = [fruit for fruit in fruits] #list using loops which is slower than array's also seperates the element(seperator)
print("Speed of list is slower than array",list)
'''
    2.Numpy array leverages complied C and fortran code for array operations, avoiding type checking and making
        it many times faster for numerical computational.
        It performs element wise operations in a more optimized manner. 
    Example:
'''
array_list = np.arange(10) * 2 # much faster than the lists
print("speed of array is faster than lists",array_list)
'''
3.Vectorization:
    1. Python list require looops or list comprehension to perform element-wise operations, which are not optimized.
   Example:
'''
list1 = [i*2 for i in range(5)] #list using loops which is slower than array's also seperates the element(seperator)
print("For loop in list: ",list1, "x2")
'''
    2.Numpy arrays leverage vectorization, which allows operations to be applied to entire arrays at once,
        without loops. 
        This leads to faster and more exploiting low-level optimizations such as SIMD (single instruction Multiple Data)
'''
array_list1 = np.arange(5) * 2 # much faster than the lists
print("vectorization in array",array_list1, "x2")
'''
4.Built in functions for numerical operations:
    1.python lists require looping or external libraries for complex mathematical functions,
        for eg: matrix, multiplication, trigonometric functions, etc.
    '''
list_1 = [1, 2, 3]
list_2 = [4, 5, 6]
dot_product = [x*y for x, y in zip(list_1, list_2)]
print("dot product using built in function in list",dot_product) #slower than array built in function
'''
    2.Numpy array have a large collections of builtin mathematical functions, that are optimized for performance,
        for eg: np.mean, np.add, np.dot, etc
        These functions can process large datasets much faster than manual loops using python lists.
    Example:
    '''
array_list_1 = [1, 2, 3]
array_list_2 = [4, 5, 6]
dot_products = np.dot(array_list_1, array_list_2)
print("dot product using array built in function", dot_products) #faster than list built in function
'''
Insights:
    For large scale numerical operations, numpy outperforms python lists due to its memory efficiency, execution speed,
        vectorization and optimized built-in functions.
'''
print()

Memory used for  [1, 2, 3, 4, 5] is 88 bytes
Memory used for array [1, 2, 3, 4, 5] is 104 bytes
Speed of list is slower than array ['Apple', 'greenapple', 'pineapple']
speed of array is faster than lists [ 0  2  4  6  8 10 12 14 16 18]
For loop in list:  [0, 2, 4, 6, 8] x2
vectorization in array [0 2 4 6 8] x2
dot product using built in function in list [4, 10, 18]
dot product using array built in function 32



In [3]:
'''
Q7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.?
Answer:
    vstack() (verticla stack) and hstack() (horizontal stack) in Numpy are used to combine arrays, 
    but they differ in how they allign the data.
    
    The difference between them are as following:
1.vstack():
    1.vertical stacks arrays, meaning it places them on the top of each other.
    2. It requires the array to have the same number of columns.
Example:
'''
array_1 = np.array([[1,2],
                   [3, 4]])
array_2 = np.array([[5, 6],
                  [7, 9]])
# Vertical stack the arrays
result_vstack  = np.vstack((array_1, array_2))
print("vertical stack of both array's\n",result_vstack)
'''
In this example, array_2 is stacked below array_1, forming a 3x2 matrix

2.hstack():
    1.Horizontally stacks array, meaning it places them side by side.
    2.It requires the arrays to have thesame number of rows.
Example:
'''
array1 = [[11, 12],
          [13, 14]]
array2 = [[16, 17],
          [18, 19]]
hstack_result = np.hstack((array1, array2))
printing_hstack = "horizontal stack of both array "
print(printing_hstack,"\n", hstack_result)
'''
Here array2 is stacked to the right of array1, resulting in a 2x4 matrix.

Key differences:
    1.Direction:
        1.vstack() stacks array vertically (one below the other).
        2.hstack() stacks arrays horizontally (side by side).
    2.Dimension Requirement:
        1.vstack() needs the array to have the same number of columns.
        2.hstack() needs the arrays to have the same number of rows.
        
Insights:
    The choice betweeen vstack() and hstack() depends on how you want to align your data.
    *Use vstacks() when you want to combine arrays along the vertical axis(stacking them on top of each other)
        and hstack() for combining along the horizontal axis (side by side).
'''
print()



vertical stack of both array's
 [[1 2]
 [3 4]
 [5 6]
 [7 9]]
horizontal stack of both array  
 [[11 12 16 17]
 [13 14 18 19]]



In [4]:
'''
Q8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.
Answer:
    In numpy, fliplr() (flip left right) and flupud() (flip up and down) are two methods used to reverse the elements
    of an array, but they do so in different directions
How do they differ area s following:
    1. fliplr() Flip Left-Right:
        1.Purpose: It flips the array horizontally, meaning it reverse the order of columns
        2.Effect: This method works on 2D array and flips the comlumns of the array, making
        the leftmost column become the rightmost one.
    Example:
'''
array = [[1, 2, 3],
         [4, 5, 6]]
flip_left_right = np.fliplr(array)
print("Flipping the array" ,array, "left to right\n", flip_left_right)
'''
    2.flipud() (Flip Up_down):
        1.purpose: It flips the array vertically, meaning it reverse the order of rows.
        2.Effect: This method flips the rows of the array, so the topmost row becomes the bottommost one.
    Example:
'''
array_ = [[1,2],
          [3, 4]]
flip_up_down = np.flipud(array_)
print("Flipping the array" ,array_, "Up to down\n", flip_up_down)
'''
Effect on various Array Dimension:
    1.1D array: 
        1.Neither method affects a 1D arrray, as flipping a 1D array left-to-right or up_to_down,
        has no meaning. 
    2.2D array:
        1.fliplr() flips the columns, so the horizontal structure changes.
        2. flipud() flips the rows, so the vertical structure changes.
    3.Higher Dimensional arrays:
        1.These functions can be applied to higher dimensional arrays, but the behaviour depends on the first two 
            dimensions(rows and columns). They do not affect the other dimension

Key Difference:
    1.fliplr() affects the columns (horizontal flip)
    2.flipud() affects the rows (vertical flip).
    
Insights:
    choosing between fliplr() and flipud() depends on whether you need to reverse an array's horizontal or
    vertical structure.
    For multidimensional array's their effects is constrained to the first two dimensions.
'''
print()


Flipping the array [[1, 2, 3], [4, 5, 6]] left to right
 [[3 2 1]
 [6 5 4]]
Flipping the array [[1, 2], [3, 4]] Up to down
 [[3 4]
 [1 2]]



In [5]:
'''
Q9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
Answer:
    The array_split() method in numpy, is used to split an array into multiple sub-arrays.
    Its functionality is similar to split(), but with an important difference: It can handle uneven splits.
Functionality:
    1.Purpose: It splits an array in to a specified number of sub-arrays, the number of splits is determined by the
    second argument passed to the method.
Syntax:
    #np.array_split(array, sections)
    1.array:The array you want to spit.
    2.sections: The number of the parts you want to split the array into.

Handling Uneven Splits:
    If the array cannot be split evenly( eg: the total number of elements cannot be evenly divided by the 
    number of sections), array_split() handles this by creating smaller sub-arrays for the remainder

    It distributes the extra elements to some sub-array.
    Sub array at the start will have one extra element if the split is uneven
Example: lets say we have an array with 10 elements and we want to split it into 3 parts, which is not evenly divisible.
'''
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 11])
print("Original array before splitting",array)

# Applying array_split() to the array
result_1 = np.array_split(array,3)
result_2 = np.array_split(array,2)
print("Array after splitting unevenly:",result_1)
#output: [array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 11])]
print("Array after splitting evenly:",result_2)
# output: [array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 11])]
'''
In this example:
    1.The first sub array gets 4 elements
    2. The secondand third sub-arrays get 3 elements each, which handles the uneven split.
comparison with split():
    1. spit() raises an error if the array cannot be divided evenly.
    2.array_split() does not raise an error, instead it adjust the split bu distributing the extra elements across 
    the first few sub-arrays.

Insights:
    The array_split() method is useful when you need flexible splitting of arrays, especially when the size of
    the array is not perfectly divisible by the number of sections.
    Its ability to handle uneven splits makes it more versatile than split(). especially for real-world data where
     perfect divisible is rare.
'''
print()

Original array before splitting [ 1  2  3  4  5  6  7  8  9 11]
Array after splitting unevenly: [array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 11])]
Array after splitting evenly: [array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 11])]



In [8]:
'''
Q10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?
Answers:
    1.Vectorization in Numpy:
        vectorization refers to the process of applying operations to entire arrays without using 
        explicit loops.
        It leverages low-level optimizations in the numpy library to make array opearions faster
        and more efficient.
        
        Instead of iterating through each element manually , numpy allows you to perform mathematical
        operations on whole array at once.
        
        Vectorization is implementing under the hood in numpy using highly optimized C and fortran libraries, 
        which is significantly speeds up computation
    Example
'''
# Withour vectorinization
arr = [1,2,3,4,5]
result = []
for i in arr:
    result.append(i*2)
print("Without Vectorization",result)

# With vectorization
arr_1 = [1, 2, 3, 4, 5]
vecto = np.array(arr_1) * 2
print("With Vectorization",vecto)
'''
Benefits:
    Vectorization operations are not only easier to write and read but also much faster because they avoid python loops
    and directly utilize optimized numpy methods.

    BroadCasting in Numpy:
        Broadcasting allows numpy to perform operations between arrays of different shapes in a way that they
        are "stretched" or "broadcasted" to a compatible shape.
        It avoids the need for manual reshaping or replication of smaller arrays, saving memory and computational 
        loads(operations).
Example:
'''
array = np.array([1,2,3])
scalar = 5
result = array + scalar
print("Broadcasted aarrya",result)
'''
In this example, the 5 is broadcasted to match the shape (3, ) so that element-wise addition can occur.

Broadcasting Rules:
    1.If two arrays have different numbers of dimension, Numpy pads the shape of the smaller array with ones on its
    left side.
    2.numpy compares shaped element-wise starting from the right, if dimensions are equal or one of them is 1,
    the array are compatible.
    3. If the array are compatible, they are virtually expanded (broadcasted) to the larger array's shape for the 
    operation.
Example:(Broadcasting with multi dimensional arrays)
'''
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b = np.array([1, 0, 1,0])
result = a + b
print("Broadcasted result\n",result)
'''
In this example: b is broadcasted to match the shape (2, 4) before element wise addition is performed.

Contribution to Efficient Array Operations:
    1.Speed: both vectorization and broadcasting eliminates the need for explicit loops,
    making the operations faster as they leverage low-level optimizations.
    2.memory efficiency: broadcasting avoids the need to create large temporary arrays by virtually expanding smaller
    manner, which makes code easier to maintain and understand.
    
Insights:
    Together, vectorization and broadcasting form the backbone of efficient array operations in numpy.
    They allow for concise, high performance code, making Numpy an essential tool for numerical computing.
    These features optimize both computation time and memory usage, which is particularly beneficial for handling 
    large datasets in machine learning and scientific applications.
'''
print()

Without Vectorization [2, 4, 6, 8, 10]
With Vectorization [ 2  4  6  8 10]
Broadcasted aarrya [6 7 8]
Broadcasted result
 [[2 2 4 4]
 [6 6 8 8]]

