In [2]:
'''
module_6
NumPy Assignment
Practical_part
'''
import numpy as np

In [10]:
'''
Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
Answer:
   To create a 3x3 Numpy arrray with random integers between 1 and 100 and then interchange its rows and columns.
   The code is as following in the form of, 
Example:
'''
# Creates a 3x3 Numpy array with random integers between 1 and 100
random_integers = np.random.randint(1, 101, size=(3, 3))
print("Original Array:\n", random_integers)

# Interchanging the original array using transposed method/function in Numpy library
array_transpose = np.transpose(random_integers)
print("Interchanged array:\n", array_transpose)
'''
Explanation:
    1.I generated a 3x3 Numpy array filled with random integers from 1 to 100.
    2.Then i print the original array in the console.
    3. to interchange rows and columns, I used np.transpose() function which swaps rows with columns.

Insights:
    Transposing a matrix is a common operation in data analysis and manipulation, allowing you to reorient your data
    for better insights or to meet specific requirements in processing or visualization .
    '''
print()

Original Array:
 [[24 46 26]
 [65 69 18]
 [95 25 70]]
Interchanged array:
 [[24 65 95]
 [46 69 25]
 [26 18 70]]



In [16]:
'''
Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

Answer:
    To generate a 1D array with 10 elements and reshape it first into a 2x5 array and then into a 5x2 array.
    The codes are as following.
Example:
    '''
# Creating a one dimensional array using arange()  function
one_dimension_array = np.arange(1, 11)
print("One dimensional array\n",one_dimension_array)

# Reshaping the array in to 2 dimensional array (2x5), butto stay in the 1d after changing the shape,You use Flatten().
reshaping_one_dimension_array = np.reshape(one_dimension_array, (2, 5))
print("Reshaped into 2 dimensional array (2x5 array\n", reshaping_one_dimension_array)

# Reshaping the array in to 2 dimensional array (5x2)
return_reshaping = np.reshape(reshaping_one_dimension_array, (5, 2))
print("Reshaped into 2 dimensional array (5x2) array\n",return_reshaping)
'''
Explanation
    1.I use np.arange(1, 11) to generate a 1d elements form 1 to 100.
    2. Then using np.reshape(array, (2, 5)), the 1d array is reshaped into a 2x5 array rows.
    3.Then i reshaped the 2x5 array into 5x2 array (5rows and 2 columns) using np.reshape(array,(5, 2)).

Insights:
    The ability to reshape arrays in Numpy allows for flexible manipulation of data, making it easy to adjust 
    the structure of datasets for analysing , visualization, or computational purpose.
    You can move between dimensions based on the data's needs while preserving the total number of elements. 
'''
print()

One dimensional array
 [ 1  2  3  4  5  6  7  8  9 10]
Reshaped into 2 dimensional array (2x5 array
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Reshaped into 2 dimensional array (5x2) array
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]



In [5]:
'''
3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
Answer:
    1. Creating an array with random floating-point values:
'''
random_array = np.random.rand(4, 4)
print("Wihtout border\n",random_array)
'''
Then, add a border of zeros around it, so it becomes a 6x6 array
'''
paddind_around = np.pad(random_array,mode="constant", pad_width=1, constant_values=0)
print("With Zeros border\n",paddind_around)
'''
This code willl give you a 6x6 array with random floating values inside and zeros around it'''

'''
Insights:
    By using np.pad(), we can efficiently modify arrays by adding borders or paddding,
    which is use full in tasks like image processing or matrix operations where we need to surround 
    data with zero values for edge handling or filtering purposes.
'''
print()

Wihtout border
 [[0.06802679 0.52661735 0.4274409  0.7480169 ]
 [0.55680899 0.50119039 0.04964722 0.67697533]
 [0.83530696 0.31564964 0.34695768 0.13545862]
 [0.30701996 0.67518993 0.49303064 0.25729982]]
With Zeros border
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.06802679 0.52661735 0.4274409  0.7480169  0.        ]
 [0.         0.55680899 0.50119039 0.04964722 0.67697533 0.        ]
 [0.         0.83530696 0.31564964 0.34695768 0.13545862 0.        ]
 [0.         0.30701996 0.67518993 0.49303064 0.25729982 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]



In [4]:
'''
Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
Answer:
    To create an array of integers from 10 to 60 with the step of 5 using numpy,
    we can utilize the np.arange() function. 
    This function generates values in a specific range with a defined step size.
Example
'''
number_array = np.arange(10, 65, 5)
print(number_array)
'''
Expalanation:
    np.arange(10, 60, 5) creates an array starting at 10 and ending before 65, incrementing by 5 in each step.
        The output will be:[10 15 20 25 30 35 40 45 50 55 60]
        This function is use ful for generating sequence of numbers efficiently.

Insights:
    By using np.arange() with a step of 5, you can easily create a sequence of numbers at regular intervals,
    making it useful for tasks like generating evenly spaced data for analysis or simulations.
'''
print()

[10 15 20 25 30 35 40 45 50 55 60]



In [5]:
'''
Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.
Answer:
    To create a Numpy array of strings and apply different case transformations to each element, 
    you can use various string methods available in python.
Example:
'''
# list of strings
array_of_strings = ["pyhton", "numpy", "pandas"]

# Applying different case transformation

# To upper_case
to_upper = np.char.upper(array_of_strings)
print(to_upper)

# To capitalized first letter
to_capitalize = np.char.capitalize(array_of_strings)
print(to_capitalize)

#To lower_case
to_lower = np.char.lower(array_of_strings)
print(to_lower)

# To title_case
to_title = np.char.title(array_of_strings)
print(to_title)
'''
Explanation:
    1.Create an Numpy Array with strings:
    2.Apply transformation using np.char.upper(), we convert all characters in the strings to uppercase
    3.Applying transformation using np.char.capitalize, 
        we converted all the characters in the stings to capitalized case.
    4.Appliying transformation using np.char.lower(), we converted all the characters in the strings to lowercase
    5. Applying transformation using np.char.title, we converted all the characters in the strings to titlecase 
    
Insights:
    Using Numpy's string function, you cann easily manipulate string data in bulk.
    this is particularly useful for data preprocessing in data analysis and machine learning,
    where consistent formatting of often required
    '''
print()


['PYHTON' 'NUMPY' 'PANDAS']
['Pyhton' 'Numpy' 'Pandas']
['pyhton' 'numpy' 'pandas']
['Pyhton' 'Numpy' 'Pandas']



In [6]:
'''
Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
Answer:
    To genrate a Numpy array of words and insert a space between each character of every word in the array,
    you can use the np.char.join() function.
    The use of this function for generating words and inserting space in between is as following:
Example: 
'''
array_of_words = ["Asad", "ahmed", "Patel", "python", "Numpy"] # creating an list of words
array_spaced_words = np.char.join(" ", array_of_words) # inserting space in between each character.
print(array_spaced_words) # printing it to the console

# Displaying th Results:
print("Original Array:" ,array_of_words)
print("Spaced Array:" ,array_spaced_words)
'''
Explanation:
    1.Creating the numpy array with words inserted in a list.
    2.Inserting a space between each character of words in the array.
    3.Displaying the original array and the spaced array with spaces in the console.

Insights:
    Using Numpy string manipulation functions, you can efficient modify text in bulk.
    This approach is particularly useful for preparing data for visualization or formatting, 
        where you may need to adjust how strings are displayed.
    '''
print()

['A s a d' 'a h m e d' 'P a t e l' 'p y t h o n' 'N u m p y']
Original Array: ['Asad', 'ahmed', 'Patel', 'python', 'Numpy']
Spaced Array: ['A s a d' 'a h m e d' 'P a t e l' 'p y t h o n' 'N u m p y']



In [17]:
'''
Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
ANswer:
    To create two 2D arrays in Numpy and performing elements-wise addition, subtraction, multiplication and divide
    are as following:
Example:
'''
arr1 = np.array([[11, 12], [13, 14]])
arr2 = np.array([[9, 8], [7, 6,]])
print("2Dimenational Array are:", arr1, "and", arr2)

#adding both the arrays element_wise:
adding_arrays = np.add(arr1, arr2)

#Subracting both the arrays
subtract_array = np.subtract(arr1, arr2)

# Both Multiplied Array
multiply_array = np.multiply(arr1, arr2)

# Divide both arrays
divide_array = np.divide(arr1, arr2)

# Displayin the Results:
print("Added Array is:\n", adding_arrays)
print("Subtracted array is:\n" , subtract_array)
print("Multiplied Array is:\n" , multiply_array)
print("Divided Array is:\n",divide_array)
'''
Explanation:
    1.np.add() adds corresponding elements from both arrays.
    2.np.subtract() subtracts corresponding elements.
    3. np.multiply() multiplied the corresponding elements .
    3. np.divide() divide both arrays corresponding elements. 
Insights:
    Element_wise operations in Numpy allow you to perform arithemetic directly on arrays, making it efficient,
    for mathematical computations in data analysis and scientific computing.
'''
print()

2Dimenational Array are: [[11 12]
 [13 14]] and [[9 8]
 [7 6]]
Added Array is:
 [[20 20]
 [20 20]]
Subtracted array is:
 [[2 4]
 [6 8]]
Multiplied Array is:
 [[99 96]
 [91 84]]
Divided Array is:
 [[1.22222222 1.5       ]
 [1.85714286 2.33333333]]



In [19]:
'''
Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements
Answer:
    The code of creating an identity matrix using Numpy and extracts its diagonal elements are as following;
Example:
'''
# Generating identity matrix suing np.eye()
identity_matrix = np.eye(5)
diagonal_elements = np.diag(identity_matrix)
print(f"identity_matrix:\n{identity_matrix}",)
print(f"Diagonal elements are:\n{diagonal_elements}")
'''
Explanation:
    1.The np.eye() function generated a 5x5 matrix, where all the diagonal elements are 1 and non-diagonal elements are 0.
    2.Then np.diag() function extracts the diagonal elements of the matrix. In this case they are all 1s.
    
Insights:
    The identity matrix is a fundamental concept in linear algebra, where diagonal elements are all ones.
    Extracting the diagonal can be useful in matrix computations, especially in eigenvalue problems and for
    checking if a matrix is an identity matrix
'''
print()

identity_matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal elements are:
[1. 1. 1. 1. 1.]



In [21]:
'''
Q9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.
Answer:
    To generate a numpy array of 100 random integers between 0 to 1000 then find and display all prime numbers
    in that array,
    code are as following performing this action( to check if the number is prime and print it in the console)
Example Code:
'''
# Generating 100 random number from 0 to 1000
random_numbers = np.random.randint(0, 1001, size= 100)

# Displaying the Random integers generated
print("Random integers are: \n", random_numbers)

# Using a function to check from the generated random number which are the prime numbers
def is_prime(num):
    if num <=1:
        return False
    for i in range(2, int(num**0.5) +1):
        if num % i == 0:
            return False
    return True

# Using list comprihension for checking the prime number using creating a loop through function
checking_prime = [num for num in random_numbers if is_prime(num)]

# Displaying the Prime Numbers
print("Random generated Prime numbers are:\n" ,[int(num) for num in checking_prime]) # using loop for readibility of the code
'''
Explanation:
    1. np.random.randint(0, 1001, size = 100) , this generated an array of 100 integers in the range
        from 0 to 1000.
    2.The is_prime(n) function checks if n is a prime number by testing divisibility from 2 up to the square root of n.
    3. The i use a list comprehension to filter out prime prime numbers from the random integers using the 
        is_prime function

'''
print()

Random integers are: 
 [ 846  673  903  168  758  898  452  950  376   43  137   86   41  459
  289   64  745  705  870  488  612  185  762 1000  128  829  519  698
  945  927  213  816  940   96  266  415  752   26  967  131  277  755
  679  259  753  884  530  936   74   55  214  711  168  941  315  111
  697  755  880  166  283  994  743  974  908  356   48  631   64  499
  693  556  702  120  232  448   53  417  303  375   64  404  570   67
  442  975  278  853  128  580  593  264  636   21  966  268  681  664
  769  755]
Random generated Prime numbers are:
 [673, 43, 137, 41, 829, 967, 131, 277, 941, 283, 743, 631, 499, 53, 67, 853, 593, 769]



In [22]:
'''
10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.?
'''
import numpy as np

# Random daily temperatures for 30 days
daily_temperatures = np.random.randint(20, 40, size=30)  # Assuming temperatures between 20°C and 40°C
print("Daily Temperatures for the Month:\n", daily_temperatures)

# First 28 days reshape for 4 full weeks
weekly_temperatures = daily_temperatures[:28].reshape(4, 7)

# Calculate weekly averages for the first 4 weeks
weekly_averages = weekly_temperatures.mean(axis=1)

# Handling the last 2 days 
last_week_average = daily_temperatures[28:].mean()

# Display the weekly averages
for i, avg in enumerate(weekly_averages, 1):
    print(f"Week {i} average temperature: {avg:.2f}°C")

# Displaying the average for the last few days
print(f"Last 2 days average temperature: {last_week_average:.2f}°C")
'''
Explanation:
    1.Daily Temperatures: Generates random temperatures for 30 days.
    2.Weekly Calculation: The first 28 days are reshaped into 4 weeks, and their averages are calculated.
    3.Last 2 Days: The average for the last 2 days is calculated separately.
Insights:
    by using Numpy , we can efficiently work with arrays representing large data sets like daily temperatures,
    Reshaping and calculating weekly averages allows for organised analysis of data over specific time perious.
    this approach is highly efficient and scalable for similar tasks involving time series data.
'''
print()

Daily Temperatures for the Month:
 [29 39 32 31 24 37 25 32 25 33 33 39 37 22 21 34 31 39 21 23 21 23 39 38
 22 30 34 39 32 38]
Week 1 average temperature: 31.00°C
Week 2 average temperature: 31.57°C
Week 3 average temperature: 27.14°C
Week 4 average temperature: 32.14°C
Last 2 days average temperature: 35.00°C

